postgresql:
  enabled: true
  image:
    repository: bitnami/postgresql
    tag: latest
  persistence:
    enabled: true
    size: 10Gi
    storageClass: managed-premium
  database: pokemondb
  username: postgres
  password: postgres
  
api:
  image:
    repository: pokemontrainer.azurecr.io/containergroup
    tag: api-amd64
  replicaCount: 1
  service:
    type: LoadBalancer
    ports:
      http: 8080
      https: 5077
  connectionString:
    host: "postgresql"  # This will be prefixed with release name
    database: "pokemondb"
    username: "postgres"
    password: "postgres"

migrations:
  image:
    repository: pokemontrainer.azurecr.io/containergroup
    tag: migrations-amd64
  # Add the same connection string config for migrations
  connectionString:
    host: "postgresql"
    database: "pokemondb"
    username: "postgres"
    password: "postgres"

pgadmin:
  enabled: true
  image:
    repository: dpage/pgadmin4
    tag: latest
  persistence:
    enabled: true
    size: 1Gi
  credentials:
    email: admin@poke.com
    password: 09Prototype_101
  service:
    type: LoadBalancer
    port: 5000