apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.environment | default "Development" }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.database }}
  POSTGRESQL_USERNAME: {{ .Values.postgresql.username }}
  POSTGRESQL_HOST: {{ .Release.Name }}-postgresql