# templates/pgadmin-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-pgadmin
spec:
  type: LoadBalancer
  ports:
    - port: 5000
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ .Release.Name }}-pgadmin
  