apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
type: Opaque
data:
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.credentials.email | b64enc }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.credentials.password | b64enc }}